add_newline = false

format = """$character"""
right_format = """$all"""

#command_timeout = 1000

#[battery]
#full_symbol = "F"
#charging_symbol = "C"
#discharging_symbol = "D"
#
#[[battery.display]]
#threshold = 10
#style = "bold red"
#
#[[battery.display]]
#threshold = 60
#style = "bold yellow"
#
#[[battery.display]]
#threshold = 100
#style = "bold green"

[character]
success_symbol = "[ğŸ’](bold green)"
error_symbol = "[ğŸ’¥](bold red)"

[cmd_duration]
min_time = 5000
format = " [$duration]($style) "

[directory]
truncation_length = 4
format = "ï“ [$path]($style)[$lock_symbol]($lock_style) "

#[directory]
#truncation_length = 6
#truncate_to_repo = true
#prefix = "in "
#style = "bold cyan"
#disabled = false

# [env_var]
# variable = "SHELL"
# default = "Zsh"
# prefix = "<"
# suffix = ">"

[fill]
symbol = " "

[git_branch]
symbol = "ğŸŒ± "
#truncation_length = 8
#truncation_symbol = "..."
style = "bold purple"

[git_state]
cherry_pick = "CHERRY PICKING"
rebase = "REBASING"
merge = "MERGING"
revert = "REVERTING"
bisect = "BISECTING"
am = "AM"
am_or_rebase = "AM/REBASE"
#progress_divider = " of "
style = "bold yellow"
disabled = false

#fix
#[git_status]
#conflicted = "âš”ï¸ "
#ahead = "ğŸï¸ ğŸ’¨ Ã—${count}"
#behind = "ğŸ¢ Ã—${count}"
#diverged = "ğŸ”± ğŸï¸ ğŸ’¨ Ã—${ahead_count} ğŸ¢ Ã—${behind_count}"
#untracked = "ğŸ›¤ï¸  Ã—${count}"
#stashed = "ğŸ“¦ "
#modified = "ğŸ“ Ã—${count}"
#staged = "ğŸ—ƒï¸  Ã—${count}"
#renamed = "ğŸ“› Ã—${count}"
#deleted = "ğŸ—‘ï¸  Ã—${count}"
#style = "bright-white"
#format = "$all_status$ahead_behind "
#
# [[git_status.count]]
# enabled = true

#sortout
#[hostname]
#ssh_only = true
#prefix = "ğŸ¤–"
## suffix = "âŸ«"
#trim_at = "."
#disabled = false
#
## [jobs]
# symbol = "+ "
# threshold = 1

[line_break]
disabled = true

#[nodejs]
#symbol = "â¬¢ "
#style = "bold green"
#disabled = false
#
#[package]
## symbol = "ğŸ“¦ "
## style = "bold red"
#disabled = true
#
#[python]
#symbol = "ğŸ "
#pyenv_version_name = false
#pyenv_prefix = "pyenv"
#style = "bold yellow"
#disabled = false

[username]
style_user = "bold red"
show_always = false
format = "[$user]($style) "

[time]
time_format = "%T"
format = "âŒš$time($style) "
style = "bright-white"
disabled = false

#[memory_usage]
#format = "$symbol[${ram}( | ${swap})]($style) "
#threshold = 70
#style = "bold dimmed white"
#disabled = false

